language: node_js
node_js:
  - "0.11"
  - "0.10"

env:
  global:
    - secure: "MGnf7sSNDhCvP/q5Ui4tZIxNLHELEbUG/2xaU1idM8wgfQxbdUInG26FPt0F08ZE5qmc6mbE/FoHOrnRUKmko1YqeJZXck+S+nohgzGuBbDcKHcsPrYsK83SsnkL+8bgPsqkS205nI411ZlaNlxRp4o5xG+u6BTaEDomHo03488="


# ~*** ------------------------------------------------->
#
# IMPORTANT NOTE:
#
# Please don't change this file manually!
# It is automatically compiled from `.travis.yml.tpl`
# in order to encrypt sensitive information using the
# repo public key.
#
# Change `.travis.yml.tpl` instead.
#
# <--------------------------------------------------- ***~


