language: node_js
node_js:
  - "0.11"
  - "0.10"

env:
  global:
    - secure: "b04a3ogSeyAoNut+Dbh1NgUXZ1od95DW3dKBIEgmbNvKNNCsWjNOC4X8KbDOaKvbTDdK+2h5UDhZ/L3iv0rpm09tPqFpGKYTH6vrAzjHRPqo7tg6oCu8cSomFLdMjorOKZk8Pe7EfzL/0a8jUG4RykvQ5NsetkMxNEpBhp5Hldc="


# ~*** ------------------------------------------------->
#
# IMPORTANT NOTE:
#
# Please don't change this file manually!
# It is automatically compiled from `.travis.yml.tpl`
# in order to encrypt sensitive information using the
# repo public key.
#
# Change `.travis.yml.tpl` instead.
#
# <--------------------------------------------------- ***~


